let
    #"Table1" = Table.FromColumns({Lines.FromBinary(File.Contents("data.txt"), null, null, 1252)}),
    #"Split1" = Table.SplitColumn(#"Table1", "Column1", Splitter.SplitTextByPositions({0, 60}, false), {"State Jurisdiction Name", "Column2"}),
    #"Table2" = Table.TransformColumnTypes(#"Split1", {{"State Jurisdiction Name", type text}, {"Column2", type text}}),
    #"Split2" = Table.SplitColumn(#"Table2", "Column2", Splitter.SplitTextByPositions({0, 60}, false), {"County Jurisdiction Name", "Column3"}),
    #"Table3" = Table.TransformColumnTypes(#"Split2", {{"County Jurisdiction Name", type text}, {"Column3", type text}}),
    #"Split3" = Table.SplitColumn(#"Table3", "Column3", Splitter.SplitTextByPositions({0, 60}, false), {"City Jurisdiction Name", "Column4"}),
    #"Table4" = Table.TransformColumnTypes(#"Split3", {{"City Jurisdiction Name", type text}, {"Column4", type text}}),
    #"Split4" = Table.SplitColumn(#"Table4", "Column4", Splitter.SplitTextByPositions({0, 15}, false), {"Company Code", "Column5"}),
    #"Table5" = Table.TransformColumnTypes(#"Split4", {{"Company Code", type text}, {"Column5", type text}}),
    #"Split5" = Table.SplitColumn(#"Table5", "Column5", Splitter.SplitTextByPositions({0, 15}, false), {"Division Code", "Column6"}),
    #"Table6" = Table.TransformColumnTypes(#"Split5", {{"Division Code", type text}, {"Column6", type text}}),
    #"Split6" = Table.SplitColumn(#"Table6", "Column6", Splitter.SplitTextByPositions({0, 15}, false), {"Department Code", "Column7"}),
    #"Table7" = Table.TransformColumnTypes(#"Split6", {{"Department Code", type text}, {"Column7", type text}}),
    #"Split7" = Table.SplitColumn(#"Table7", "Column7", Splitter.SplitTextByPositions({0, 5}, false), {"Tax Category Code", "Column8"}),
    #"Table8" = Table.TransformColumnTypes(#"Split7", {{"Tax Category Code", type text}, {"Column8", type text}}),
    #"Split8" = Table.SplitColumn(#"Table8", "Column8", Splitter.SplitTextByPositions({0, 15}, false), {"Location Code", "Column9"}),
    #"Table9" = Table.TransformColumnTypes(#"Split8", {{"Location Code", type text}, {"Column9", type text}}),
    #"Split9" = Table.SplitColumn(#"Table9", "Column9", Splitter.SplitTextByPositions({0, 1}, false), {"Record Type", "Column10"}),
    #"Table10" = Table.TransformColumnTypes(#"Split9", {{"Record Type", type text}, {"Column10", type text}}),
    #"Split10" = Table.SplitColumn(#"Table10", "Column10", Splitter.SplitTextByPositions({0, 15}, false), {"Taxable State", "Column11"}),
    #"Table11" = Table.TransformColumnTypes(#"Split10", {{"Taxable State", type number}, {"Column11", type text}}),
    #"Split11" = Table.SplitColumn(#"Table11", "Column11", Splitter.SplitTextByPositions({0, 15}, false), {"Taxable County", "Column12"}),
    #"Table12" = Table.TransformColumnTypes(#"Split11", {{"Taxable County", type number}, {"Column12", type text}}),
    #"Split12" = Table.SplitColumn(#"Table12", "Column12", Splitter.SplitTextByPositions({0, 15}, false), {"Taxable City", "Column13"}),
    #"Table13" = Table.TransformColumnTypes(#"Split12", {{"Taxable City", type number}, {"Column13", type text}}),
    #"Split13" = Table.SplitColumn(#"Table13", "Column13", Splitter.SplitTextByPositions({0, 15}, false), {"Taxable District", "Column14"}),
    #"Table14" = Table.TransformColumnTypes(#"Split13", {{"Taxable District", type number}, {"Column14", type text}}),
    #"Split14" = Table.SplitColumn(#"Table14", "Column14", Splitter.SplitTextByPositions({0, 15}, false), {"Tax State", "Column15"}),
    #"Table15" = Table.TransformColumnTypes(#"Split14", {{"Tax State", type number}, {"Column15", type text}}),
    #"Split15" = Table.SplitColumn(#"Table15", "Column15", Splitter.SplitTextByPositions({0, 15}, false), {"Tax County", "Column16"}),
    #"Table16" = Table.TransformColumnTypes(#"Split15", {{"Tax County", type number}, {"Column16", type text}}),
    #"Split16" = Table.SplitColumn(#"Table16", "Column16", Splitter.SplitTextByPositions({0, 15}, false), {"Tax City", "Column17"}),
    #"Table17" = Table.TransformColumnTypes(#"Split16", {{"Tax City", type number}, {"Column17", type text}}),
    #"Split17" = Table.SplitColumn(#"Table17", "Column17", Splitter.SplitTextByPositions({0, 15}, false), {"Tax District", "Column18"}),
    #"Table18" = Table.TransformColumnTypes(#"Split17", {{"Tax District", type number}, {"Column18", type text}}),
    #"Split18" = Table.SplitColumn(#"Table18", "Column18", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount State (1)", "Column19"}),
    #"Table19" = Table.TransformColumnTypes(#"Split18", {{"Exempt Amount State (1)", type number}, {"Column19", type text}}),
    #"Split19" = Table.SplitColumn(#"Table19", "Column19", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code State (1)", "Column20"}),
    #"Table20" = Table.TransformColumnTypes(#"Split19", {{"Exempt Code State (1)", type text}, {"Column20", type text}}),
    #"Split20" = Table.SplitColumn(#"Table20", "Column20", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount County (1)", "Column21"}),
    #"Table21" = Table.TransformColumnTypes(#"Split20", {{"Exempt Amount County (1)", type number}, {"Column21", type text}}),
    #"Split21" = Table.SplitColumn(#"Table21", "Column21", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code County (1)", "Column22"}),
    #"Table22" = Table.TransformColumnTypes(#"Split21", {{"Exempt Code County (1)", type text}, {"Column22", type text}}),
    #"Split22" = Table.SplitColumn(#"Table22", "Column22", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount City (1)", "Column23"}),
    #"Table23" = Table.TransformColumnTypes(#"Split22", {{"Exempt Amount City (1)", type number}, {"Column23", type text}}),
    #"Split23" = Table.SplitColumn(#"Table23", "Column23", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code City (1)", "Column24"}),
    #"Table24" = Table.TransformColumnTypes(#"Split23", {{"Exempt Code City (1)", type text}, {"Column24", type text}}),
    #"Split24" = Table.SplitColumn(#"Table24", "Column24", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount District (1)", "Column25"}),
    #"Table25" = Table.TransformColumnTypes(#"Split24", {{"Exempt Amount District (1)", type number}, {"Column25", type text}}),
    #"Split25" = Table.SplitColumn(#"Table25", "Column25", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code District (1)", "Column26"}),
    #"Table26" = Table.TransformColumnTypes(#"Split25", {{"Exempt Code District (1)", type text}, {"Column26", type text}}),
    #"Split26" = Table.SplitColumn(#"Table26", "Column26", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount State (2)", "Column27"}),
    #"Table27" = Table.TransformColumnTypes(#"Split26", {{"Exempt Amount State (2)", type number}, {"Column27", type text}}),
    #"Split27" = Table.SplitColumn(#"Table27", "Column27", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code State (2)", "Column28"}),
    #"Table28" = Table.TransformColumnTypes(#"Split27", {{"Exempt Code State (2)", type text}, {"Column28", type text}}),
    #"Split28" = Table.SplitColumn(#"Table28", "Column28", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount County (2)", "Column29"}),
    #"Table29" = Table.TransformColumnTypes(#"Split28", {{"Exempt Amount County (2)", type number}, {"Column29", type text}}),
    #"Split29" = Table.SplitColumn(#"Table29", "Column29", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code County (2)", "Column30"}),
    #"Table30" = Table.TransformColumnTypes(#"Split29", {{"Exempt Code County (2)", type text}, {"Column30", type text}}),
    #"Split30" = Table.SplitColumn(#"Table30", "Column30", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount City (2)", "Column31"}),
    #"Table31" = Table.TransformColumnTypes(#"Split30", {{"Exempt Amount City (2)", type number}, {"Column31", type text}}),
    #"Split31" = Table.SplitColumn(#"Table31", "Column31", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code City (2)", "Column32"}),
    #"Table32" = Table.TransformColumnTypes(#"Split31", {{"Exempt Code City (2)", type text}, {"Column32", type text}}),
    #"Split32" = Table.SplitColumn(#"Table32", "Column32", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount District (2)", "Column33"}),
    #"Table33" = Table.TransformColumnTypes(#"Split32", {{"Exempt Amount District (2)", type number}, {"Column33", type text}}),
    #"Split33" = Table.SplitColumn(#"Table33", "Column33", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code District (2)", "Column34"}),
    #"Table34" = Table.TransformColumnTypes(#"Split33", {{"Exempt Code District (2)", type text}, {"Column34", type text}}),
    #"Split34" = Table.SplitColumn(#"Table34", "Column34", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount State (3)", "Column35"}),
    #"Table35" = Table.TransformColumnTypes(#"Split34", {{"Exempt Amount State (3)", type number}, {"Column35", type text}}),
    #"Split35" = Table.SplitColumn(#"Table35", "Column35", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code State (3)", "Column36"}),
    #"Table36" = Table.TransformColumnTypes(#"Split35", {{"Exempt Code State (3)", type text}, {"Column36", type text}}),
    #"Split36" = Table.SplitColumn(#"Table36", "Column36", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount County (3)", "Column37"}),
    #"Table37" = Table.TransformColumnTypes(#"Split36", {{"Exempt Amount County (3)", type number}, {"Column37", type text}}),
    #"Split37" = Table.SplitColumn(#"Table37", "Column37", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code County (3)", "Column38"}),
    #"Table38" = Table.TransformColumnTypes(#"Split37", {{"Exempt Code County (3)", type text}, {"Column38", type text}}),
    #"Split38" = Table.SplitColumn(#"Table38", "Column38", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount City (3)", "Column39"}),
    #"Table39" = Table.TransformColumnTypes(#"Split38", {{"Exempt Amount City (3)", type number}, {"Column39", type text}}),
    #"Split39" = Table.SplitColumn(#"Table39", "Column39", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code City (3)", "Column40"}),
    #"Table40" = Table.TransformColumnTypes(#"Split39", {{"Exempt Code City (3)", type text}, {"Column40", type text}}),
    #"Split40" = Table.SplitColumn(#"Table40", "Column40", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount District (3)", "Column41"}),
    #"Table41" = Table.TransformColumnTypes(#"Split40", {{"Exempt Amount District (3)", type number}, {"Column41", type text}}),
    #"Split41" = Table.SplitColumn(#"Table41", "Column41", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code District (3)", "Column42"}),
    #"Table42" = Table.TransformColumnTypes(#"Split41", {{"Exempt Code District (3)", type text}, {"Column42", type text}}),
    #"Split42" = Table.SplitColumn(#"Table42", "Column42", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount State (4)", "Column43"}),
    #"Table43" = Table.TransformColumnTypes(#"Split42", {{"Exempt Amount State (4)", type number}, {"Column43", type text}}),
    #"Split43" = Table.SplitColumn(#"Table43", "Column43", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code State (4)", "Column44"}),
    #"Table44" = Table.TransformColumnTypes(#"Split43", {{"Exempt Code State (4)", type text}, {"Column44", type text}}),
    #"Split44" = Table.SplitColumn(#"Table44", "Column44", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount County (4)", "Column45"}),
    #"Table45" = Table.TransformColumnTypes(#"Split44", {{"Exempt Amount County (4)", type number}, {"Column45", type text}}),
    #"Split45" = Table.SplitColumn(#"Table45", "Column45", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code County (4)", "Column46"}),
    #"Table46" = Table.TransformColumnTypes(#"Split45", {{"Exempt Code County (4)", type text}, {"Column46", type text}}),
    #"Split46" = Table.SplitColumn(#"Table46", "Column46", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount City (4)", "Column47"}),
    #"Table47" = Table.TransformColumnTypes(#"Split46", {{"Exempt Amount City (4)", type number}, {"Column47", type text}}),
    #"Split47" = Table.SplitColumn(#"Table47", "Column47", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code City (4)", "Column48"}),
    #"Table48" = Table.TransformColumnTypes(#"Split47", {{"Exempt Code City (4)", type text}, {"Column48", type text}}),
    #"Split48" = Table.SplitColumn(#"Table48", "Column48", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount District (4)", "Column49"}),
    #"Table49" = Table.TransformColumnTypes(#"Split48", {{"Exempt Amount District (4)", type number}, {"Column49", type text}}),
    #"Split49" = Table.SplitColumn(#"Table49", "Column49", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code District (4)", "Column50"}),
    #"Table50" = Table.TransformColumnTypes(#"Split49", {{"Exempt Code District (4)", type text}, {"Column50", type text}}),
    #"Split50" = Table.SplitColumn(#"Table50", "Column50", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount State (5)", "Column51"}),
    #"Table51" = Table.TransformColumnTypes(#"Split50", {{"Exempt Amount State (5)", type number}, {"Column51", type text}}),
    #"Split51" = Table.SplitColumn(#"Table51", "Column51", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code State (5)", "Column52"}),
    #"Table52" = Table.TransformColumnTypes(#"Split51", {{"Exempt Code State (5)", type text}, {"Column52", type text}}),
    #"Split52" = Table.SplitColumn(#"Table52", "Column52", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount County (5)", "Column53"}),
    #"Table53" = Table.TransformColumnTypes(#"Split52", {{"Exempt Amount County (5)", type number}, {"Column53", type text}}),
    #"Split53" = Table.SplitColumn(#"Table53", "Column53", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code County (5)", "Column54"}),
    #"Table54" = Table.TransformColumnTypes(#"Split53", {{"Exempt Code County (5)", type text}, {"Column54", type text}}),
    #"Split54" = Table.SplitColumn(#"Table54", "Column54", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount City (5)", "Column55"}),
    #"Table55" = Table.TransformColumnTypes(#"Split54", {{"Exempt Amount City (5)", type number}, {"Column55", type text}}),
    #"Split55" = Table.SplitColumn(#"Table55", "Column55", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code City (5)", "Column56"}),
    #"Table56" = Table.TransformColumnTypes(#"Split55", {{"Exempt Code City (5)", type text}, {"Column56", type text}}),
    #"Split56" = Table.SplitColumn(#"Table56", "Column56", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount District (5)", "Column57"}),
    #"Table57" = Table.TransformColumnTypes(#"Split56", {{"Exempt Amount District (5)", type number}, {"Column57", type text}}),
    #"Split57" = Table.SplitColumn(#"Table57", "Column57", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code District (5)", "Column58"}),
    #"Table58" = Table.TransformColumnTypes(#"Split57", {{"Exempt Code District (5)", type text}, {"Column58", type text}}),
    #"Split58" = Table.SplitColumn(#"Table58", "Column58", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount State (6)", "Column59"}),
    #"Table59" = Table.TransformColumnTypes(#"Split58", {{"Exempt Amount State (6)", type number}, {"Column59", type text}}),
    #"Split59" = Table.SplitColumn(#"Table59", "Column59", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code State (6)", "Column60"}),
    #"Table60" = Table.TransformColumnTypes(#"Split59", {{"Exempt Code State (6)", type text}, {"Column60", type text}}),
    #"Split60" = Table.SplitColumn(#"Table60", "Column60", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount County (6)", "Column61"}),
    #"Table61" = Table.TransformColumnTypes(#"Split60", {{"Exempt Amount County (6)", type number}, {"Column61", type text}}),
    #"Split61" = Table.SplitColumn(#"Table61", "Column61", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code County (6)", "Column62"}),
    #"Table62" = Table.TransformColumnTypes(#"Split61", {{"Exempt Code County (6)", type text}, {"Column62", type text}}),
    #"Split62" = Table.SplitColumn(#"Table62", "Column62", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount City (6)", "Column63"}),
    #"Table63" = Table.TransformColumnTypes(#"Split62", {{"Exempt Amount City (6)", type number}, {"Column63", type text}}),
    #"Split63" = Table.SplitColumn(#"Table63", "Column63", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code City (6)", "Column64"}),
    #"Table64" = Table.TransformColumnTypes(#"Split63", {{"Exempt Code City (6)", type text}, {"Column64", type text}}),
    #"Split64" = Table.SplitColumn(#"Table64", "Column64", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount District (6)", "Column65"}),
    #"Table65" = Table.TransformColumnTypes(#"Split64", {{"Exempt Amount District (6)", type number}, {"Column65", type text}}),
    #"Split65" = Table.SplitColumn(#"Table65", "Column65", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code District (6)", "Column66"}),
    #"Table66" = Table.TransformColumnTypes(#"Split65", {{"Exempt Code District (6)", type text}, {"Column66", type text}}),
    #"Split66" = Table.SplitColumn(#"Table66", "Column66", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount State (7)", "Column67"}),
    #"Table67" = Table.TransformColumnTypes(#"Split66", {{"Exempt Amount State (7)", type number}, {"Column67", type text}}),
    #"Split67" = Table.SplitColumn(#"Table67", "Column67", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code State (7)", "Column68"}),
    #"Table68" = Table.TransformColumnTypes(#"Split67", {{"Exempt Code State (7)", type text}, {"Column68", type text}}),
    #"Split68" = Table.SplitColumn(#"Table68", "Column68", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount County (7)", "Column69"}),
    #"Table69" = Table.TransformColumnTypes(#"Split68", {{"Exempt Amount County (7)", type number}, {"Column69", type text}}),
    #"Split69" = Table.SplitColumn(#"Table69", "Column69", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code County (7)", "Column70"}),
    #"Table70" = Table.TransformColumnTypes(#"Split69", {{"Exempt Code County (7)", type text}, {"Column70", type text}}),
    #"Split70" = Table.SplitColumn(#"Table70", "Column70", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount City (7)", "Column71"}),
    #"Table71" = Table.TransformColumnTypes(#"Split70", {{"Exempt Amount City (7)", type number}, {"Column71", type text}}),
    #"Split71" = Table.SplitColumn(#"Table71", "Column71", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code City (7)", "Column72"}),
    #"Table72" = Table.TransformColumnTypes(#"Split71", {{"Exempt Code City (7)", type text}, {"Column72", type text}}),
    #"Split72" = Table.SplitColumn(#"Table72", "Column72", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount District (7)", "Column73"}),
    #"Table73" = Table.TransformColumnTypes(#"Split72", {{"Exempt Amount District (7)", type number}, {"Column73", type text}}),
    #"Split73" = Table.SplitColumn(#"Table73", "Column73", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code District (7)", "Column74"}),
    #"Table74" = Table.TransformColumnTypes(#"Split73", {{"Exempt Code District (7)", type text}, {"Column74", type text}}),
    #"Split74" = Table.SplitColumn(#"Table74", "Column74", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount State (8)", "Column75"}),
    #"Table75" = Table.TransformColumnTypes(#"Split74", {{"Exempt Amount State (8)", type number}, {"Column75", type text}}),
    #"Split75" = Table.SplitColumn(#"Table75", "Column75", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code State (8)", "Column76"}),
    #"Table76" = Table.TransformColumnTypes(#"Split75", {{"Exempt Code State (8)", type text}, {"Column76", type text}}),
    #"Split76" = Table.SplitColumn(#"Table76", "Column76", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount County (8)", "Column77"}),
    #"Table77" = Table.TransformColumnTypes(#"Split76", {{"Exempt Amount County (8)", type number}, {"Column77", type text}}),
    #"Split77" = Table.SplitColumn(#"Table77", "Column77", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code County (8)", "Column78"}),
    #"Table78" = Table.TransformColumnTypes(#"Split77", {{"Exempt Code County (8)", type text}, {"Column78", type text}}),
    #"Split78" = Table.SplitColumn(#"Table78", "Column78", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount City (8)", "Column79"}),
    #"Table79" = Table.TransformColumnTypes(#"Split78", {{"Exempt Amount City (8)", type number}, {"Column79", type text}}),
    #"Split79" = Table.SplitColumn(#"Table79", "Column79", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code City (8)", "Column80"}),
    #"Table80" = Table.TransformColumnTypes(#"Split79", {{"Exempt Code City (8)", type text}, {"Column80", type text}}),
    #"Split80" = Table.SplitColumn(#"Table80", "Column80", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount District (8)", "Column81"}),
    #"Table81" = Table.TransformColumnTypes(#"Split80", {{"Exempt Amount District (8)", type number}, {"Column81", type text}}),
    #"Split81" = Table.SplitColumn(#"Table81", "Column81", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code District (8)", "Column82"}),
    #"Table82" = Table.TransformColumnTypes(#"Split81", {{"Exempt Code District (8)", type text}, {"Column82", type text}}),
    #"Split82" = Table.SplitColumn(#"Table82", "Column82", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount State (9)", "Column83"}),
    #"Table83" = Table.TransformColumnTypes(#"Split82", {{"Exempt Amount State (9)", type number}, {"Column83", type text}}),
    #"Split83" = Table.SplitColumn(#"Table83", "Column83", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code State (9)", "Column84"}),
    #"Table84" = Table.TransformColumnTypes(#"Split83", {{"Exempt Code State (9)", type text}, {"Column84", type text}}),
    #"Split84" = Table.SplitColumn(#"Table84", "Column84", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount County (9)", "Column85"}),
    #"Table85" = Table.TransformColumnTypes(#"Split84", {{"Exempt Amount County (9)", type number}, {"Column85", type text}}),
    #"Split85" = Table.SplitColumn(#"Table85", "Column85", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code County (9)", "Column86"}),
    #"Table86" = Table.TransformColumnTypes(#"Split85", {{"Exempt Code County (9)", type text}, {"Column86", type text}}),
    #"Split86" = Table.SplitColumn(#"Table86", "Column86", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount City (9)", "Column87"}),
    #"Table87" = Table.TransformColumnTypes(#"Split86", {{"Exempt Amount City (9)", type number}, {"Column87", type text}}),
    #"Split87" = Table.SplitColumn(#"Table87", "Column87", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code City (9)", "Column88"}),
    #"Table88" = Table.TransformColumnTypes(#"Split87", {{"Exempt Code City (9)", type text}, {"Column88", type text}}),
    #"Split88" = Table.SplitColumn(#"Table88", "Column88", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount District (9)", "Column89"}),
    #"Table89" = Table.TransformColumnTypes(#"Split88", {{"Exempt Amount District (9)", type number}, {"Column89", type text}}),
    #"Split89" = Table.SplitColumn(#"Table89", "Column89", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code District (9)", "Column90"}),
    #"Table90" = Table.TransformColumnTypes(#"Split89", {{"Exempt Code District (9)", type text}, {"Column90", type text}}),
    #"Split90" = Table.SplitColumn(#"Table90", "Column90", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount State (10)", "Column91"}),
    #"Table91" = Table.TransformColumnTypes(#"Split90", {{"Exempt Amount State (10)", type number}, {"Column91", type text}}),
    #"Split91" = Table.SplitColumn(#"Table91", "Column91", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code State (10)", "Column92"}),
    #"Table92" = Table.TransformColumnTypes(#"Split91", {{"Exempt Code State (10)", type text}, {"Column92", type text}}),
    #"Split92" = Table.SplitColumn(#"Table92", "Column92", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount County (10)", "Column93"}),
    #"Table93" = Table.TransformColumnTypes(#"Split92", {{"Exempt Amount County (10)", type number}, {"Column93", type text}}),
    #"Split93" = Table.SplitColumn(#"Table93", "Column93", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code County (10)", "Column94"}),
    #"Table94" = Table.TransformColumnTypes(#"Split93", {{"Exempt Code County (10)", type text}, {"Column94", type text}}),
    #"Split94" = Table.SplitColumn(#"Table94", "Column94", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount City (10)", "Column95"}),
    #"Table95" = Table.TransformColumnTypes(#"Split94", {{"Exempt Amount City (10)", type number}, {"Column95", type text}}),
    #"Split95" = Table.SplitColumn(#"Table95", "Column95", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code City (10)", "Column96"}),
    #"Table96" = Table.TransformColumnTypes(#"Split95", {{"Exempt Code City (10)", type text}, {"Column96", type text}}),
    #"Split96" = Table.SplitColumn(#"Table96", "Column96", Splitter.SplitTextByPositions({0, 15}, false), {"Exempt Amount District (10)", "Column97"}),
    #"Table97" = Table.TransformColumnTypes(#"Split96", {{"Exempt Amount District (10)", type number}, {"Column97", type text}}),
    #"Split97" = Table.SplitColumn(#"Table97", "Column97", Splitter.SplitTextByPositions({0, 4}, false), {"Exempt Code District (10)", "Column98"}),
    #"Table98" = Table.TransformColumnTypes(#"Split97", {{"Exempt Code District (10)", type text}, {"Column98", type text}}),
    #"Split98" = Table.SplitColumn(#"Table98", "Column98", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount State (1)", "Column99"}),
    #"Table99" = Table.TransformColumnTypes(#"Split98", {{"Non Taxable Amount State (1)", type number}, {"Column99", type text}}),
    #"Split99" = Table.SplitColumn(#"Table99", "Column99", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code State (1)", "Column100"}),
    #"Table100" = Table.TransformColumnTypes(#"Split99", {{"Non Taxable Code State (1)", type text}, {"Column100", type text}}),
    #"Split100" = Table.SplitColumn(#"Table100", "Column100", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount County (1)", "Column101"}),
    #"Table101" = Table.TransformColumnTypes(#"Split100", {{"Non Taxable Amount County (1)", type number}, {"Column101", type text}}),
    #"Split101" = Table.SplitColumn(#"Table101", "Column101", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code County (1)", "Column102"}),
    #"Table102" = Table.TransformColumnTypes(#"Split101", {{"Non Taxable Code County (1)", type text}, {"Column102", type text}}),
    #"Split102" = Table.SplitColumn(#"Table102", "Column102", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount City (1)", "Column103"}),
    #"Table103" = Table.TransformColumnTypes(#"Split102", {{"Non Taxable Amount City (1)", type number}, {"Column103", type text}}),
    #"Split103" = Table.SplitColumn(#"Table103", "Column103", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code City (1)", "Column104"}),
    #"Table104" = Table.TransformColumnTypes(#"Split103", {{"Non Taxable Code City (1)", type text}, {"Column104", type text}}),
    #"Split104" = Table.SplitColumn(#"Table104", "Column104", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount District (1)", "Column105"}),
    #"Table105" = Table.TransformColumnTypes(#"Split104", {{"Non Taxable Amount District (1)", type number}, {"Column105", type text}}),
    #"Split105" = Table.SplitColumn(#"Table105", "Column105", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code District (1)", "Column106"}),
    #"Table106" = Table.TransformColumnTypes(#"Split105", {{"Non Taxable Code District (1)", type text}, {"Column106", type text}}),
    #"Split106" = Table.SplitColumn(#"Table106", "Column106", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount State (2)", "Column107"}),
    #"Table107" = Table.TransformColumnTypes(#"Split106", {{"Non Taxable Amount State (2)", type number}, {"Column107", type text}}),
    #"Split107" = Table.SplitColumn(#"Table107", "Column107", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code State (2)", "Column108"}),
    #"Table108" = Table.TransformColumnTypes(#"Split107", {{"Non Taxable Code State (2)", type text}, {"Column108", type text}}),
    #"Split108" = Table.SplitColumn(#"Table108", "Column108", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount County (2)", "Column109"}),
    #"Table109" = Table.TransformColumnTypes(#"Split108", {{"Non Taxable Amount County (2)", type number}, {"Column109", type text}}),
    #"Split109" = Table.SplitColumn(#"Table109", "Column109", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code County (2)", "Column110"}),
    #"Table110" = Table.TransformColumnTypes(#"Split109", {{"Non Taxable Code County (2)", type text}, {"Column110", type text}}),
    #"Split110" = Table.SplitColumn(#"Table110", "Column110", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount City (2)", "Column111"}),
    #"Table111" = Table.TransformColumnTypes(#"Split110", {{"Non Taxable Amount City (2)", type number}, {"Column111", type text}}),
    #"Split111" = Table.SplitColumn(#"Table111", "Column111", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code City (2)", "Column112"}),
    #"Table112" = Table.TransformColumnTypes(#"Split111", {{"Non Taxable Code City (2)", type text}, {"Column112", type text}}),
    #"Split112" = Table.SplitColumn(#"Table112", "Column112", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount District (2)", "Column113"}),
    #"Table113" = Table.TransformColumnTypes(#"Split112", {{"Non Taxable Amount District (2)", type number}, {"Column113", type text}}),
    #"Split113" = Table.SplitColumn(#"Table113", "Column113", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code District (2)", "Column114"}),
    #"Table114" = Table.TransformColumnTypes(#"Split113", {{"Non Taxable Code District (2)", type text}, {"Column114", type text}}),
    #"Split114" = Table.SplitColumn(#"Table114", "Column114", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount State (3)", "Column115"}),
    #"Table115" = Table.TransformColumnTypes(#"Split114", {{"Non Taxable Amount State (3)", type number}, {"Column115", type text}}),
    #"Split115" = Table.SplitColumn(#"Table115", "Column115", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code State (3)", "Column116"}),
    #"Table116" = Table.TransformColumnTypes(#"Split115", {{"Non Taxable Code State (3)", type text}, {"Column116", type text}}),
    #"Split116" = Table.SplitColumn(#"Table116", "Column116", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount County (3)", "Column117"}),
    #"Table117" = Table.TransformColumnTypes(#"Split116", {{"Non Taxable Amount County (3)", type number}, {"Column117", type text}}),
    #"Split117" = Table.SplitColumn(#"Table117", "Column117", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code County (3)", "Column118"}),
    #"Table118" = Table.TransformColumnTypes(#"Split117", {{"Non Taxable Code County (3)", type text}, {"Column118", type text}}),
    #"Split118" = Table.SplitColumn(#"Table118", "Column118", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount City (3)", "Column119"}),
    #"Table119" = Table.TransformColumnTypes(#"Split118", {{"Non Taxable Amount City (3)", type number}, {"Column119", type text}}),
    #"Split119" = Table.SplitColumn(#"Table119", "Column119", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code City (3)", "Column120"}),
    #"Table120" = Table.TransformColumnTypes(#"Split119", {{"Non Taxable Code City (3)", type text}, {"Column120", type text}}),
    #"Split120" = Table.SplitColumn(#"Table120", "Column120", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount District (3)", "Column121"}),
    #"Table121" = Table.TransformColumnTypes(#"Split120", {{"Non Taxable Amount District (3)", type number}, {"Column121", type text}}),
    #"Split121" = Table.SplitColumn(#"Table121", "Column121", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code District (3)", "Column122"}),
    #"Table122" = Table.TransformColumnTypes(#"Split121", {{"Non Taxable Code District (3)", type text}, {"Column122", type text}}),
    #"Split122" = Table.SplitColumn(#"Table122", "Column122", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount State (4)", "Column123"}),
    #"Table123" = Table.TransformColumnTypes(#"Split122", {{"Non Taxable Amount State (4)", type number}, {"Column123", type text}}),
    #"Split123" = Table.SplitColumn(#"Table123", "Column123", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code State (4)", "Column124"}),
    #"Table124" = Table.TransformColumnTypes(#"Split123", {{"Non Taxable Code State (4)", type text}, {"Column124", type text}}),
    #"Split124" = Table.SplitColumn(#"Table124", "Column124", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount County (4)", "Column125"}),
    #"Table125" = Table.TransformColumnTypes(#"Split124", {{"Non Taxable Amount County (4)", type number}, {"Column125", type text}}),
    #"Split125" = Table.SplitColumn(#"Table125", "Column125", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code County (4)", "Column126"}),
    #"Table126" = Table.TransformColumnTypes(#"Split125", {{"Non Taxable Code County (4)", type text}, {"Column126", type text}}),
    #"Split126" = Table.SplitColumn(#"Table126", "Column126", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount City (4)", "Column127"}),
    #"Table127" = Table.TransformColumnTypes(#"Split126", {{"Non Taxable Amount City (4)", type number}, {"Column127", type text}}),
    #"Split127" = Table.SplitColumn(#"Table127", "Column127", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code City (4)", "Column128"}),
    #"Table128" = Table.TransformColumnTypes(#"Split127", {{"Non Taxable Code City (4)", type text}, {"Column128", type text}}),
    #"Split128" = Table.SplitColumn(#"Table128", "Column128", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount District (4)", "Column129"}),
    #"Table129" = Table.TransformColumnTypes(#"Split128", {{"Non Taxable Amount District (4)", type number}, {"Column129", type text}}),
    #"Split129" = Table.SplitColumn(#"Table129", "Column129", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code District (4)", "Column130"}),
    #"Table130" = Table.TransformColumnTypes(#"Split129", {{"Non Taxable Code District (4)", type text}, {"Column130", type text}}),
    #"Split130" = Table.SplitColumn(#"Table130", "Column130", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount State (5)", "Column131"}),
    #"Table131" = Table.TransformColumnTypes(#"Split130", {{"Non Taxable Amount State (5)", type number}, {"Column131", type text}}),
    #"Split131" = Table.SplitColumn(#"Table131", "Column131", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code State (5)", "Column132"}),
    #"Table132" = Table.TransformColumnTypes(#"Split131", {{"Non Taxable Code State (5)", type text}, {"Column132", type text}}),
    #"Split132" = Table.SplitColumn(#"Table132", "Column132", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount County (5)", "Column133"}),
    #"Table133" = Table.TransformColumnTypes(#"Split132", {{"Non Taxable Amount County (5)", type number}, {"Column133", type text}}),
    #"Split133" = Table.SplitColumn(#"Table133", "Column133", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code County (5)", "Column134"}),
    #"Table134" = Table.TransformColumnTypes(#"Split133", {{"Non Taxable Code County (5)", type text}, {"Column134", type text}}),
    #"Split134" = Table.SplitColumn(#"Table134", "Column134", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount City (5)", "Column135"}),
    #"Table135" = Table.TransformColumnTypes(#"Split134", {{"Non Taxable Amount City (5)", type number}, {"Column135", type text}}),
    #"Split135" = Table.SplitColumn(#"Table135", "Column135", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code City (5)", "Column136"}),
    #"Table136" = Table.TransformColumnTypes(#"Split135", {{"Non Taxable Code City (5)", type text}, {"Column136", type text}}),
    #"Split136" = Table.SplitColumn(#"Table136", "Column136", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount District (5)", "Column137"}),
    #"Table137" = Table.TransformColumnTypes(#"Split136", {{"Non Taxable Amount District (5)", type number}, {"Column137", type text}}),
    #"Split137" = Table.SplitColumn(#"Table137", "Column137", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code District (5)", "Column138"}),
    #"Table138" = Table.TransformColumnTypes(#"Split137", {{"Non Taxable Code District (5)", type text}, {"Column138", type text}}),
    #"Split138" = Table.SplitColumn(#"Table138", "Column138", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount State (6)", "Column139"}),
    #"Table139" = Table.TransformColumnTypes(#"Split138", {{"Non Taxable Amount State (6)", type number}, {"Column139", type text}}),
    #"Split139" = Table.SplitColumn(#"Table139", "Column139", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code State (6)", "Column140"}),
    #"Table140" = Table.TransformColumnTypes(#"Split139", {{"Non Taxable Code State (6)", type text}, {"Column140", type text}}),
    #"Split140" = Table.SplitColumn(#"Table140", "Column140", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount County (6)", "Column141"}),
    #"Table141" = Table.TransformColumnTypes(#"Split140", {{"Non Taxable Amount County (6)", type number}, {"Column141", type text}}),
    #"Split141" = Table.SplitColumn(#"Table141", "Column141", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code County (6)", "Column142"}),
    #"Table142" = Table.TransformColumnTypes(#"Split141", {{"Non Taxable Code County (6)", type text}, {"Column142", type text}}),
    #"Split142" = Table.SplitColumn(#"Table142", "Column142", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount City (6)", "Column143"}),
    #"Table143" = Table.TransformColumnTypes(#"Split142", {{"Non Taxable Amount City (6)", type number}, {"Column143", type text}}),
    #"Split143" = Table.SplitColumn(#"Table143", "Column143", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code City (6)", "Column144"}),
    #"Table144" = Table.TransformColumnTypes(#"Split143", {{"Non Taxable Code City (6)", type text}, {"Column144", type text}}),
    #"Split144" = Table.SplitColumn(#"Table144", "Column144", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount District (6)", "Column145"}),
    #"Table145" = Table.TransformColumnTypes(#"Split144", {{"Non Taxable Amount District (6)", type number}, {"Column145", type text}}),
    #"Split145" = Table.SplitColumn(#"Table145", "Column145", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code District (6)", "Column146"}),
    #"Table146" = Table.TransformColumnTypes(#"Split145", {{"Non Taxable Code District (6)", type text}, {"Column146", type text}}),
    #"Split146" = Table.SplitColumn(#"Table146", "Column146", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount State (7)", "Column147"}),
    #"Table147" = Table.TransformColumnTypes(#"Split146", {{"Non Taxable Amount State (7)", type number}, {"Column147", type text}}),
    #"Split147" = Table.SplitColumn(#"Table147", "Column147", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code State (7)", "Column148"}),
    #"Table148" = Table.TransformColumnTypes(#"Split147", {{"Non Taxable Code State (7)", type text}, {"Column148", type text}}),
    #"Split148" = Table.SplitColumn(#"Table148", "Column148", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount County (7)", "Column149"}),
    #"Table149" = Table.TransformColumnTypes(#"Split148", {{"Non Taxable Amount County (7)", type number}, {"Column149", type text}}),
    #"Split149" = Table.SplitColumn(#"Table149", "Column149", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code County (7)", "Column150"}),
    #"Table150" = Table.TransformColumnTypes(#"Split149", {{"Non Taxable Code County (7)", type text}, {"Column150", type text}}),
    #"Split150" = Table.SplitColumn(#"Table150", "Column150", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount City (7)", "Column151"}),
    #"Table151" = Table.TransformColumnTypes(#"Split150", {{"Non Taxable Amount City (7)", type number}, {"Column151", type text}}),
    #"Split151" = Table.SplitColumn(#"Table151", "Column151", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code City (7)", "Column152"}),
    #"Table152" = Table.TransformColumnTypes(#"Split151", {{"Non Taxable Code City (7)", type text}, {"Column152", type text}}),
    #"Split152" = Table.SplitColumn(#"Table152", "Column152", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount District (7)", "Column153"}),
    #"Table153" = Table.TransformColumnTypes(#"Split152", {{"Non Taxable Amount District (7)", type number}, {"Column153", type text}}),
    #"Split153" = Table.SplitColumn(#"Table153", "Column153", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code District (7)", "Column154"}),
    #"Table154" = Table.TransformColumnTypes(#"Split153", {{"Non Taxable Code District (7)", type text}, {"Column154", type text}}),
    #"Split154" = Table.SplitColumn(#"Table154", "Column154", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount State (8)", "Column155"}),
    #"Table155" = Table.TransformColumnTypes(#"Split154", {{"Non Taxable Amount State (8)", type number}, {"Column155", type text}}),
    #"Split155" = Table.SplitColumn(#"Table155", "Column155", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code State (8)", "Column156"}),
    #"Table156" = Table.TransformColumnTypes(#"Split155", {{"Non Taxable Code State (8)", type text}, {"Column156", type text}}),
    #"Split156" = Table.SplitColumn(#"Table156", "Column156", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount County (8)", "Column157"}),
    #"Table157" = Table.TransformColumnTypes(#"Split156", {{"Non Taxable Amount County (8)", type number}, {"Column157", type text}}),
    #"Split157" = Table.SplitColumn(#"Table157", "Column157", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code County (8)", "Column158"}),
    #"Table158" = Table.TransformColumnTypes(#"Split157", {{"Non Taxable Code County (8)", type text}, {"Column158", type text}}),
    #"Split158" = Table.SplitColumn(#"Table158", "Column158", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount City (8)", "Column159"}),
    #"Table159" = Table.TransformColumnTypes(#"Split158", {{"Non Taxable Amount City (8)", type number}, {"Column159", type text}}),
    #"Split159" = Table.SplitColumn(#"Table159", "Column159", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code City (8)", "Column160"}),
    #"Table160" = Table.TransformColumnTypes(#"Split159", {{"Non Taxable Code City (8)", type text}, {"Column160", type text}}),
    #"Split160" = Table.SplitColumn(#"Table160", "Column160", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount District (8)", "Column161"}),
    #"Table161" = Table.TransformColumnTypes(#"Split160", {{"Non Taxable Amount District (8)", type number}, {"Column161", type text}}),
    #"Split161" = Table.SplitColumn(#"Table161", "Column161", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code District (8)", "Column162"}),
    #"Table162" = Table.TransformColumnTypes(#"Split161", {{"Non Taxable Code District (8)", type text}, {"Column162", type text}}),
    #"Split162" = Table.SplitColumn(#"Table162", "Column162", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount State (9)", "Column163"}),
    #"Table163" = Table.TransformColumnTypes(#"Split162", {{"Non Taxable Amount State (9)", type number}, {"Column163", type text}}),
    #"Split163" = Table.SplitColumn(#"Table163", "Column163", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code State (9)", "Column164"}),
    #"Table164" = Table.TransformColumnTypes(#"Split163", {{"Non Taxable Code State (9)", type text}, {"Column164", type text}}),
    #"Split164" = Table.SplitColumn(#"Table164", "Column164", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount County (9)", "Column165"}),
    #"Table165" = Table.TransformColumnTypes(#"Split164", {{"Non Taxable Amount County (9)", type number}, {"Column165", type text}}),
    #"Split165" = Table.SplitColumn(#"Table165", "Column165", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code County (9)", "Column166"}),
    #"Table166" = Table.TransformColumnTypes(#"Split165", {{"Non Taxable Code County (9)", type text}, {"Column166", type text}}),
    #"Split166" = Table.SplitColumn(#"Table166", "Column166", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount City (9)", "Column167"}),
    #"Table167" = Table.TransformColumnTypes(#"Split166", {{"Non Taxable Amount City (9)", type number}, {"Column167", type text}}),
    #"Split167" = Table.SplitColumn(#"Table167", "Column167", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code City (9)", "Column168"}),
    #"Table168" = Table.TransformColumnTypes(#"Split167", {{"Non Taxable Code City (9)", type text}, {"Column168", type text}}),
    #"Split168" = Table.SplitColumn(#"Table168", "Column168", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount District (9)", "Column169"}),
    #"Table169" = Table.TransformColumnTypes(#"Split168", {{"Non Taxable Amount District (9)", type number}, {"Column169", type text}}),
    #"Split169" = Table.SplitColumn(#"Table169", "Column169", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code District (9)", "Column170"}),
    #"Table170" = Table.TransformColumnTypes(#"Split169", {{"Non Taxable Code District (9)", type text}, {"Column170", type text}}),
    #"Split170" = Table.SplitColumn(#"Table170", "Column170", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount State (10)", "Column171"}),
    #"Table171" = Table.TransformColumnTypes(#"Split170", {{"Non Taxable Amount State (10)", type number}, {"Column171", type text}}),
    #"Split171" = Table.SplitColumn(#"Table171", "Column171", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code State (10)", "Column172"}),
    #"Table172" = Table.TransformColumnTypes(#"Split171", {{"Non Taxable Code State (10)", type text}, {"Column172", type text}}),
    #"Split172" = Table.SplitColumn(#"Table172", "Column172", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount County (10)", "Column173"}),
    #"Table173" = Table.TransformColumnTypes(#"Split172", {{"Non Taxable Amount County (10)", type number}, {"Column173", type text}}),
    #"Split173" = Table.SplitColumn(#"Table173", "Column173", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code County (10)", "Column174"}),
    #"Table174" = Table.TransformColumnTypes(#"Split173", {{"Non Taxable Code County (10)", type text}, {"Column174", type text}}),
    #"Split174" = Table.SplitColumn(#"Table174", "Column174", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount City (10)", "Column175"}),
    #"Table175" = Table.TransformColumnTypes(#"Split174", {{"Non Taxable Amount City (10)", type number}, {"Column175", type text}}),
    #"Split175" = Table.SplitColumn(#"Table175", "Column175", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code City (10)", "Column176"}),
    #"Table176" = Table.TransformColumnTypes(#"Split175", {{"Non Taxable Code City (10)", type text}, {"Column176", type text}}),
    #"Split176" = Table.SplitColumn(#"Table176", "Column176", Splitter.SplitTextByPositions({0, 15}, false), {"Non Taxable Amount District (10)", "Column177"}),
    #"Table177" = Table.TransformColumnTypes(#"Split176", {{"Non Taxable Amount District (10)", type number}, {"Column177", type text}}),
    #"Split177" = Table.SplitColumn(#"Table177", "Column177", Splitter.SplitTextByPositions({0, 4}, false), {"Non Taxable Code District (10)", "Column178"}),
    #"Table178" = Table.TransformColumnTypes(#"Split177", {{"Non Taxable Code District (10)", type text}, {"Column178", type text}}),
    #"Split178" = Table.SplitColumn(#"Table178", "Column178", Splitter.SplitTextByPositions({0, 9}, false), {"Tax Area ID", "Column179"}),
    #"Table179" = Table.TransformColumnTypes(#"Split178", {{"Tax Area ID", type number}, {"Column179", type text}}),
    #"Split179" = Table.SplitColumn(#"Table179", "Column179", Splitter.SplitTextByPositions({0, 9}, false), {"Physical Origin Tax Area ID", "Column180"}),
    #"Table180" = Table.TransformColumnTypes(#"Split179", {{"Physical Origin Tax Area ID", type number}, {"Column180", type text}})
in
    #"Table180"

